In [73]:
pip install  pyfaidx

Requirement already satisfied: pyfaidx in /mnt/raid1/thalassini/home/anaconda3/lib/python3.11/site-packages (0.7.2.2)
Requirement already satisfied: six in /mnt/raid1/thalassini/home/anaconda3/lib/python3.11/site-packages (from pyfaidx) (1.16.0)
Requirement already satisfied: setuptools in /mnt/raid1/thalassini/home/anaconda3/lib/python3.11/site-packages (from pyfaidx) (68.0.0)
Requirement already satisfied: importlib-metadata in /mnt/raid1/thalassini/home/anaconda3/lib/python3.11/site-packages (from pyfaidx) (6.0.0)
Requirement already satisfied: zipp>=0.5 in /mnt/raid1/thalassini/home/anaconda3/lib/python3.11/site-packages (from importlib-metadata->pyfaidx) (3.11.0)
Note: you may need to restart the kernel to use updated packages.

In [184]:
pip install torch

Collecting torch
  Obtaining dependency information for torch from https://files.pythonhosted.org/packages/da/6a/7fb9d82db4568834ff6d4df2fe3b143de4ed65a3f8f93e7daed703626cb6/torch-2.1.2-cp311-cp311-manylinux1_x86_64.whl.metadata
  Downloading torch-2.1.2-cp311-cp311-manylinux1_x86_64.whl.metadata (25 kB)
Requirement already satisfied: filelock in /mnt/raid1/thalassini/home/anaconda3/lib/python3.11/site-packages (from torch) (3.9.0)
Requirement already satisfied: typing-extensions in /mnt/raid1/thalassini/home/anaconda3/lib/python3.11/site-packages (from torch) (4.7.1)
Requirement already satisfied: sympy in /mnt/raid1/thalassini/home/anaconda3/lib/python3.11/site-packages (from torch) (1.11.1)
Requirement already satisfied: networkx in /mnt/raid1/thalassini/home/anaconda3/lib/python3.11/site-packages (from torch) (3.1)
Requirement already satisfied: jinja2 in /mnt/raid1/thalassini/home/anaconda3/lib/python3.11/site-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in /mnt/raid1/thalassini/home/anaconda3/lib/python3.11/site-packages (from torch) (2023.4.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 31.3 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 73.9 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 38.9 MB/s eta 0:00:00m eta 0:00:010:01:01
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch)
  Obtaining dependency information for nvidia-cudnn-cu12==8.9.2.26 from https://files.pythonhosted.org/packages/ff/74/a2e2be7fb83aaedec84f391f082cf765dfb635e7caa9b49065f73e4835d8/nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata
  Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch)
  Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 5.5 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch)
  Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 16.8 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Collecting nvidia-curand-cu12==10.3.2.106 (from torch)
  Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 25.2 MB/s eta 0:00:00m eta 0:00:010:01:01
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch)
  Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 12.8 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch)
  Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 10.6 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Collecting nvidia-nccl-cu12==2.18.1 (from torch)
  Downloading nvidia_nccl_cu12-2.18.1-py3-none-manylinux1_x86_64.whl (209.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.8/209.8 MB 9.0 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Collecting nvidia-nvtx-cu12==12.1.105 (from torch)
  Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 31.7 MB/s eta 0:00:00
Collecting triton==2.1.0 (from torch)
  Obtaining dependency information for triton==2.1.0 from https://files.pythonhosted.org/packages/5c/c1/54fffb2eb13d293d9a429fead3646752ea190de0229bcf3d591ba2481263/triton-2.1.0-0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata
  Downloading triton-2.1.0-0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.3 kB)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch)
  Obtaining dependency information for nvidia-nvjitlink-cu12 from https://files.pythonhosted.org/packages/1e/07/bf730d44c2fe1b676ad9cc2be5f5f861eb5d153fb6951987a2d6a96379a9/nvidia_nvjitlink_cu12-12.3.101-py3-none-manylinux1_x86_64.whl.metadata
  Downloading nvidia_nvjitlink_cu12-12.3.101-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /mnt/raid1/thalassini/home/anaconda3/lib/python3.11/site-packages (from jinja2->torch) (2.1.1)
Requirement already satisfied: mpmath>=0.19 in /mnt/raid1/thalassini/home/anaconda3/lib/python3.11/site-packages (from sympy->torch) (1.3.0)
Downloading torch-2.1.2-cp311-cp311-manylinux1_x86_64.whl (670.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.2/670.2 MB 3.7 MB/s eta 0:00:000m eta 0:00:01[36m0:00:01
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 3.5 MB/s eta 0:00:000m eta 0:00:01[36m0:00:01
Downloading triton-2.1.0-0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.2/89.2 MB 16.9 MB/s eta 0:00:000m eta 0:00:010:01:01
Downloading nvidia_nvjitlink_cu12-12.3.101-py3-none-manylinux1_x86_64.whl (20.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.5/20.5 MB 56.4 MB/s eta 0:00:000m eta 0:00:010:01:01
Installing collected packages: triton, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, torch
Successfully installed nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.18.1 nvidia-nvjitlink-cu12-12.3.101 nvidia-nvtx-cu12-12.1.105 torch-2.1.2 triton-2.1.0
Note: you may need to restart the kernel to use updated packages.

In [187]:
import pandas as pd
import numpy as np

# Convert fimo.tsv to bed format

In [94]:
# Load the TSV file into a DataFrame
#file_path=input("Give fimo.tsv file path: ")
file_path = '/mnt/raid1/thalassini/home/fimo/encode_grch38_max/fimo.tsv'
df = pd.read_csv(file_path, sep='\t')
df.dropna(inplace=True)

# Display the DataFrame
df

,motif_id,motif_alt_id,sequence_name,start,stop,strand,score,p-value,q-value,matched_sequence
0,MA0139.2,CTCF,chr10,11458.0,11472.0,+,24.2951,2.930000e-10,0.026,GCCACCAGGGGGCGC
1,MA0139.2,CTCF,chr12,547112.0,547126.0,-,24.2951,2.930000e-10,0.026,GCCACCAGGGGGCGC
2,MA0139.2,CTCF,chr1,869920.0,869934.0,+,24.2951,2.930000e-10,0.026,GCCACCAGGGGGCGC
3,MA0139.2,CTCF,chr1,904770.0,904784.0,+,24.2951,2.930000e-10,0.026,GCCACCAGGGGGCGC
4,MA0139.2,CTCF,chr6,1397165.0,1397179.0,-,24.2951,2.930000e-10,0.026,GCCACCAGGGGGCGC
...,...,...,...,...,...,...,...,...,...,...
480300,MA0139.2,CTCF,chr1,245200915.0,245200929.0,-,10.0984,4.490000e-05,0.548,ATCAACAGGGGTCAC
480301,MA0139.2,CTCF,chr1,245560998.0,245561012.0,+,10.0984,4.490000e-05,0.548,AACAGAAGGTGGCCC
480302,MA0139.2,CTCF,chr1,246738775.0,246738789.0,+,10.0984,4.490000e-05,0.548,CCCGCGAGGTGGAGG
480303,MA0139.2,CTCF,chr1,247423982.0,247423996.0,+,10.0984,4.490000e-05,0.548,AGCAGGAGAGGGAGC
480304,MA0139.2,CTCF,chr1,247470114.0,247470128.0,+,10.0984,4.490000e-05,0.548,ATCACAAGAGGTCAG

## Rename columns

In [95]:
df.rename(columns={"sequence_name": "Chromosome", "start": "Start", "stop": "End"}, inplace=True)
df

,motif_id,motif_alt_id,Chromosome,Start,End,strand,score,p-value,q-value,matched_sequence
0,MA0139.2,CTCF,chr10,11458.0,11472.0,+,24.2951,2.930000e-10,0.026,GCCACCAGGGGGCGC
1,MA0139.2,CTCF,chr12,547112.0,547126.0,-,24.2951,2.930000e-10,0.026,GCCACCAGGGGGCGC
2,MA0139.2,CTCF,chr1,869920.0,869934.0,+,24.2951,2.930000e-10,0.026,GCCACCAGGGGGCGC
3,MA0139.2,CTCF,chr1,904770.0,904784.0,+,24.2951,2.930000e-10,0.026,GCCACCAGGGGGCGC
4,MA0139.2,CTCF,chr6,1397165.0,1397179.0,-,24.2951,2.930000e-10,0.026,GCCACCAGGGGGCGC
...,...,...,...,...,...,...,...,...,...,...
480300,MA0139.2,CTCF,chr1,245200915.0,245200929.0,-,10.0984,4.490000e-05,0.548,ATCAACAGGGGTCAC
480301,MA0139.2,CTCF,chr1,245560998.0,245561012.0,+,10.0984,4.490000e-05,0.548,AACAGAAGGTGGCCC
480302,MA0139.2,CTCF,chr1,246738775.0,246738789.0,+,10.0984,4.490000e-05,0.548,CCCGCGAGGTGGAGG
480303,MA0139.2,CTCF,chr1,247423982.0,247423996.0,+,10.0984,4.490000e-05,0.548,AGCAGGAGAGGGAGC
480304,MA0139.2,CTCF,chr1,247470114.0,247470128.0,+,10.0984,4.490000e-05,0.548,ATCACAAGAGGTCAG

## Convert coordinated to integers

In [96]:
df["Start"]=df["Start"].astype('int')
df["End"]=df["End"].astype('int')

## Merge "p-value, q-value & matched_sequence" in column "name"

In [97]:
# Concatenate columns into a new 'name' column
df['name'] = df['motif_alt_id'].astype(str) + '_' + df['p-value'].astype(str) + '_' + df['q-value'].astype(str) + '_' + df['matched_sequence']

# Drop the original columns
df.drop(['motif_id', 'p-value', 'q-value', 'matched_sequence', 'motif_alt_id' ], axis=1, inplace=True)

# Display the updated DataFrame with the new 'name' column and without the original col
df

,Chromosome,Start,End,strand,score,name
0,chr10,11458,11472,+,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
1,chr12,547112,547126,-,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
2,chr1,869920,869934,+,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
3,chr1,904770,904784,+,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
4,chr6,1397165,1397179,-,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
...,...,...,...,...,...,...
480300,chr1,245200915,245200929,-,10.0984,CTCF_4.49e-05_0.548_ATCAACAGGGGTCAC
480301,chr1,245560998,245561012,+,10.0984,CTCF_4.49e-05_0.548_AACAGAAGGTGGCCC
480302,chr1,246738775,246738789,+,10.0984,CTCF_4.49e-05_0.548_CCCGCGAGGTGGAGG
480303,chr1,247423982,247423996,+,10.0984,CTCF_4.49e-05_0.548_AGCAGGAGAGGGAGC
480304,chr1,247470114,247470128,+,10.0984,CTCF_4.49e-05_0.548_ATCACAAGAGGTCAG

In [98]:
columns=df.columns
columns

Index(['Chromosome', 'Start', 'End', 'strand', 'score', 'name'], dtype='object')

 ## Filter from variant chromosome names

In [99]:
#Discover the unique sequence names in fimo.tsv
for sequence_name in df['Chromosome'].unique():
    print(sequence_name)

chr10
chr12
chr1
chr6
chr4
chrX
chr16
chr20
chr22
chr19
chr3
chr7
chr11
chr8
chr14
chr17
chr13
chr2
chr9
hm
chr18
chr14_KI270726v1_random
chr15
chr16_KI270728v1_random
chr21
chr22_KI270734v1_random
chr22_KI270731v1_random
chr1_KI270714v1_random
chr15_KI270727v1_random
chrEBV
chr11_KI270721v1_random
chr14_KI270723v1_random
chr17_GL000205v2_random
chrUn_GL000218v1
chr14_GL000194v1_random
chrUn_KI270744v1
chrUn_GL000213v1
chrUn_KI270745v1
chrUn_GL000195v1
chrUn_GL000219v1
chr1_KI270712v1_random
chrUn_KI270750v1
chrUn_KI270755v1
chrUn_KI270753v1
chr22_KI270733v1_random
chr1_KI270706v1_random
chrUn_KI270748v1
chrUn_KI270741v1
chr1_KI270711v1_random
chrUn_GL000224v1
chr1_KI270708v1_random
chr14_KI270722v1_random
chr1_KI270713v1_random
chr14_KI270725v1_random
chrUn_KI270749v1
chr9_KI270717v1_random
chr14_KI270724v1_random
chrUn_KI270752v1
chrUn_KI270435v1
chrUn_KI270743v1
chr4_GL000008v2_random
chr14_GL000009v2_random
chr5_GL000208v1_random
chr14_GL000225v1_random
chrUn_GL000216v2
chrUn_GL000220v1
chr9_KI270719v1_random
chr9_KI270718v1_random
chr3_GL000221v1_random
chrUn_KI270742v1
chrUn_KI270746v1
chr22_KI270732v1_random
chr1_KI270707v1_random
chrUn_KI270747v1
chrUn_KI270315v1
chrUn_KI270304v1
chrUn_GL000214v1
chr22_KI270739v1_random
chrUn_KI270519v1
chrUn_KI270442v1
chrUn_KI270751v1
chr1_KI270709v1_random
chrUn_KI270589v1
chrUn_KI270757v1
chrUn_KI270371v1
chrUn_KI270511v1
chr1_KI270710v1_random
chrUn_KI270754v1
chr17_KI270729v1_random
chrUn_KI270539v1
chr22_KI270735v1_random
chr22_KI270738v1_random
chr22_KI270736v1_random
chr9_KI270720v1_random
chr22_KI270737v1_random
chrUn_KI270530v1
chrY_KI270740v1_random
chrUn_KI270538v1
chrUn_KI270419v1
chrUn_KI270423v1
chrUn_KI270422v1
chrUn_KI270418v1
chr17_KI270730v1_random

In [100]:
# Expected list of NCBI values
expected_list = ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12',
                 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY', 'chrM']

# Filter rows based on 'NCBI' column values matching the expected list
df = df[df['Chromosome'].isin(expected_list)]

In [101]:
df

,Chromosome,Start,End,strand,score,name
0,chr10,11458,11472,+,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
1,chr12,547112,547126,-,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
2,chr1,869920,869934,+,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
3,chr1,904770,904784,+,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
4,chr6,1397165,1397179,-,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
...,...,...,...,...,...,...
480300,chr1,245200915,245200929,-,10.0984,CTCF_4.49e-05_0.548_ATCAACAGGGGTCAC
480301,chr1,245560998,245561012,+,10.0984,CTCF_4.49e-05_0.548_AACAGAAGGTGGCCC
480302,chr1,246738775,246738789,+,10.0984,CTCF_4.49e-05_0.548_CCCGCGAGGTGGAGG
480303,chr1,247423982,247423996,+,10.0984,CTCF_4.49e-05_0.548_AGCAGGAGAGGGAGC
480304,chr1,247470114,247470128,+,10.0984,CTCF_4.49e-05_0.548_ATCACAAGAGGTCAG

## Save df as .bed

In [102]:
# Save the csv file 
df.to_csv('fimo_full.bed', sep='\t', index=False, header=False)

# Mart to bed
Convert mart_export.txt to bed format

In [103]:
import pandas as pd

# Load the TSV file into a DataFrame
#file_path=input("Give mart_export_unique.txt file path: ")
file_path = '/mnt/raid1/thalassini/home/Downloads/mart_export.txt'
mart_df = pd.read_csv(file_path, sep='\t')
mart_df.dropna(inplace=True)

# Display the DataFrame
mart_df

       Chromosome/scaffold name  Start (bp)   End (bp) Feature type
0                            18    35116801   35120999     Enhancer
1                             6    90249202   90257999     Enhancer
2                             7    39894801   39895400     Enhancer
3                            15    63059401   63062399     Enhancer
4                             3   119868001  119868400     Enhancer
...                         ...         ...        ...          ...
305075                        8    98939200   98949401     Promoter
305076                        4    39364800   39367201     Promoter
305077                        X   152752601  152755400     Promoter
305078                       16    58495400   58496001     Promoter
305079                        7    38332400   38337001     Promoter

[305080 rows x 4 columns]

In [104]:
# Mapping table
mapping_table = {
    '1': 'chr1',
    '2': 'chr2',
    '3': 'chr3',
    '4': 'chr4',
    '5': 'chr5',
    '6': 'chr6',
    '7': 'chr7',
    '8': 'chr8',
    '9': 'chr9',
    '10': 'chr10',
    '11': 'chr11',
    '12': 'chr12',
    '13': 'chr13',
    '14': 'chr14',
    '15': 'chr15',
    '16': 'chr16',
    '17': 'chr17',
    '18': 'chr18',
    '19': 'chr19',
    '20': 'chr20',
    '21': 'chr21',
    '22': 'chr22',
    'X': 'chrX',
    'Y': 'chrY',
    'MT': 'chrM'
}

In [105]:
mart_df['Chromosome/scaffold name'] = mart_df['Chromosome/scaffold name'].map(mapping_table)
mart_df

       Chromosome/scaffold name  Start (bp)   End (bp) Feature type
0                         chr18    35116801   35120999     Enhancer
1                          chr6    90249202   90257999     Enhancer
2                          chr7    39894801   39895400     Enhancer
3                         chr15    63059401   63062399     Enhancer
4                          chr3   119868001  119868400     Enhancer
...                         ...         ...        ...          ...
305075                     chr8    98939200   98949401     Promoter
305076                     chr4    39364800   39367201     Promoter
305077                     chrX   152752601  152755400     Promoter
305078                    chr16    58495400   58496001     Promoter
305079                     chr7    38332400   38337001     Promoter

[305080 rows x 4 columns]

In [106]:
# Save the csv file 
mart_df.to_csv('mart.bed', sep='\t', index=False, header=False)

# Run bedtools intesect to create filtered fimo
>> bedtools intersect -a /mnt/raid1/thalassini/home/Downloads/fimo_full.bed  -b /mnt/raid1/thalassini/home/Downloads/mart.bed > ensemlb_filtered_fimo.bed

# Display filtered_fimo df

In [107]:
# Load the BED file into a DataFrame
#file_path=input("Give ensemlb_filtered_fimo.bed file path: ")
file_path = '/mnt/raid1/thalassini/home/ensemlb_filtered_fimo.bed'
filtered_df = pd.read_csv(file_path, sep='\t')
filtered_df.dropna(inplace=True)
filtered_df.columns=columns
# Display the DataFrame
filtered_df

,Chromosome,Start,End,strand,score,name
0,chr1,869920,869934,+,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
1,chr1,904770,904784,+,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
2,chr6,1397165,1397179,-,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
3,chr4,1579280,1579294,-,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
4,chrX,9995929,9995943,+,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
...,...,...,...,...,...,...
104638,chr2,239339669,239339683,-,10.0984,CTCF_4.49e-05_0.548_GCCAGGAGATTGCAG
104639,chr2,241355101,241355115,+,10.0984,CTCF_4.49e-05_0.548_GCCACATGGTGACAG
104640,chr1,241396943,241396957,+,10.0984,CTCF_4.49e-05_0.548_GCCACATGGTGACAG
104641,chr2,241764826,241764840,-,10.0984,CTCF_4.49e-05_0.548_AGCAGGAGAGGGAGC
104642,chr1,245200915,245200929,-,10.0984,CTCF_4.49e-05_0.548_ATCAACAGGGGTCAC

In [70]:
print(f" The promoter/enhancer filtered data is reduced by {100-len(filtered_df)* 100/len(df)}% from initial fimo results")

 The promoter/enhancer filtered data is reduced by 76.8351588995245% from initial fimo results

# Run bedtools intesect to create chipseq_filtered fimo
>> bedtools intersect -a ensemlb_filtered_fimo.bed -b /mnt/raid1/thalassini/home/Downloads/ENCFF970MXD.bed > chipseq_filtered.bed

# Display chipseq_filtered df

In [108]:
# Load the BED file into a DataFrame
#file_path=input("Give chipseq_filtered_fimo.bed file path: ")
file_path = '/mnt/raid1/thalassini/home/chipseq_filtered.bed'
chipseq_filtered_df = pd.read_csv(file_path, sep='\t')
chipseq_filtered_df.dropna(inplace=True)
chipseq_filtered_df.columns=columns
# Display the DataFrame
chipseq_filtered_df

,Chromosome,Start,End,strand,score,name
0,chr1,869920,869934,+,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
1,chr1,904770,904784,+,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
2,chr6,1397165,1397179,-,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
3,chr4,1579280,1579294,-,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
4,chrX,9995929,9995943,+,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
...,...,...,...,...,...,...
17931,chr4,112637587,112637601,+,10.0984,CTCF_4.49e-05_0.548_GCCAGAAGATAGCGA
17932,chr9,122810697,122810711,-,10.0984,CTCF_4.49e-05_0.548_ACCACAATAGGGCAG
17933,chr9,122810697,122810711,-,10.0984,CTCF_4.49e-05_0.548_ACCACAATAGGGCAG
17934,chr7,131581578,131581592,+,10.0984,CTCF_4.49e-05_0.548_GCCAACAAAGGGCAG
17935,chr8,143771853,143771867,+,10.0984,CTCF_4.49e-05_0.548_AGCAGGAGGAGGCGG

In [125]:
for chromosome in chipseq_filtered_df["Chromosome"]:
    print(chipseq_filtered)

0        chr1
1        chr1
2        chr6
3        chr4
4        chrX
         ...
17931    chr4
17932    chr9
17933    chr9
17934    chr7
17935    chr8
Name: Chromosome, Length: 17936, dtype: object

In [72]:
print(f" The chipseq filtered data is reduced by {100-len(chipseq_filtered_df)* 100/len(df)}% from initial fimo results")

 The chipseq filtered data is reduced by 96.02950421931588% from initial fimo results

# Find sequence from coordinates

In [74]:
#/home/marina/Downloads/phix.fasta
from pyfaidx import Fasta

# Path to your reference genome FASTA file
reference_genome_file = '/mnt/raid1/thalassini/home/Downloads/Homo_sapiens.GRCh38.dna.toplevel.fa'



# Load the reference genome using pyfaidx
fasta = Fasta(reference_genome_file)

# List all chromosome names in the reference genome file
chromosome_names = fasta.keys()

# Display the list of chromosome names
print(chromosome_names)

odict_keys(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'MT', 'HG76_PATCH', 'HG2365_PATCH', 'HSCHR15_4_CTG8', 'HSCHR6_MHC_SSTO_CTG1', 'HSCHR6_MHC_MCF_CTG1', 'HSCHR6_MHC_COX_CTG1', 'HSCHR6_MHC_MANN_CTG1', 'HSCHR6_MHC_APD_CTG1', 'HSCHR6_MHC_QBL_CTG1', 'HSCHR6_MHC_DBB_CTG1', 'HSCHR17_7_CTG4', 'HSCHR16_1_CTG1', 'HSCHR15_6_CTG8', 'HG926_PATCH', 'HSCHR17_1_CTG5', 'HSCHR5_2_CTG1_1', 'HG1343_HG173_HG459_PATCH', 'HSCHR14_7_CTG1', 'HSCHR17_2_CTG5', 'HSCHR14_3_CTG1', 'HG2280_PATCH', 'HSCHR5_1_CTG1_1', 'HSCHR7_2_CTG6', 'HSCHR19LRC_LRC_J_CTG3_1', 'HSCHR19_4_CTG3_1', 'HSCHR19LRC_LRC_S_CTG3_1', 'HSCHR19LRC_LRC_I_CTG3_1', 'HG1815_PATCH', 'HG2265_PATCH', 'HSCHR19LRC_LRC_T_CTG3_1', 'HSCHR19LRC_COX1_CTG3_1', 'HSCHR19LRC_PGF1_CTG3_1', 'HSCHR8_8_CTG1', 'HG2275_PATCH', 'HSCHR1_3_CTG32_1', 'HSCHR6_1_CTG8', 'HG1532_PATCH', 'HSCHR1_5_CTG31', 'HSCHR19LRC_PGF2_CTG3_1', 'HSCHR19LRC_COX2_CTG3_1', 'HG2526_HG2573_PATCH', 'HG1_PATCH', 'HSCHR7_3_CTG4_4', 'HG30_PATCH', 'HSCHR8_9_CTG1', 'HSCHRX_1_CTG14', 'HG708_PATCH', 'HSCHR4_1_CTG9', 'HSCHR12_3_CTG2', 'HG1206_PATCH', 'HSCHR4_7_CTG12', 'HSCHR1_6_CTG3', 'HG1362_PATCH', 'HG2407_PATCH', 'HSCHR2_11_CTG7_2', 'HSCHR2_6_CTG7_2', 'HG2513_PATCH', 'HSCHR1_12_CTG3', 'HG2308_PATCH', 'HSCHR2_12_CTG7_2', 'HG109_PATCH', 'HG2052_PATCH', 'HG1012_PATCH', 'HG2290_PATCH', 'HG2263_PATCH', 'HSCHR15_1_CTG1', 'HG2069_PATCH', 'HG2264_PATCH', 'HG2266_PATCH', 'HG1342_HG2282_PATCH', 'HSCHR7_4_CTG1', 'HG1485_PATCH', 'HG1832_PATCH', 'HG545_PATCH', 'HG2066_PATCH', 'HSCHR9_1_CTG5', 'HG152_PATCH', 'HSCHR2_10_CTG7_2', 'HSCHR15_5_CTG8', 'HG2267_PATCH', 'HSCHR1_1_CTG32_1', 'HSCHR4_12_CTG12', 'HG2244_HG2245_PATCH', 'HG126_PATCH', 'HG2512_PATCH', 'HG2236_PATCH', 'HG2509_PATCH', 'HSCHR12_2_CTG2', 'HG2213_PATCH', 'HG26_PATCH', 'HG439_PATCH', 'HG2510_PATCH', 'HG2511_PATCH', 'HSCHR17_2_CTG2', 'HSCHR15_2_CTG8', 'HSCHR19_1_CTG2', 'HSCHR6_1_CTG1', 'HSCHR4_6_CTG12', 'HSCHR4_1_CTG6', 'HSCHR17_1_CTG1', 'HSCHR8_1_CTG7', 'HG2235_PATCH', 'HSCHR17_13_CTG4', 'HG2021_PATCH', 'HG2198_PATCH', 'HSCHR1_3_CTG31', 'HG2232_PATCH', 'HSCHR5_8_CTG1', 'HG2291_PATCH', 'HG410_PATCH', 'HSCHR1_1_CTG3', 'HSCHR1_4_CTG3', 'HG2568_PATCH', 'HG2525_PATCH', 'HG2158_PATCH', 'HG2219_PATCH', 'HSCHR1_6_CTG31', 'HG405_PATCH', 'HG2461_PATCH', 'HSCHRX_3_CTG3', 'HG2030_PATCH', 'HG2002_PATCH', 'HSCHR15_1_CTG3', 'HSCHR17_10_CTG4', 'HSCHR14_1_CTG1', 'HG1651_PATCH', 'HSCHR8_5_CTG1', 'HG2063_PATCH', 'HSCHR10_1_CTG2', 'HSCHR4_2_CTG8_1', 'HSCHR13_1_CTG1', 'HG2022_PATCH', 'HSCHR8_3_CTG7', 'HG2095_PATCH', 'HG2060_PATCH', 'HSCHR22_1_CTG7', 'HSCHR3_9_CTG2_1', 'HSCHR5_10_CTG1', 'HSCHR11_2_CTG8', 'HG2077_PATCH', 'HSCHR8_3_CTG1', 'HG2246_HG2248_HG2276_PATCH', 'HSCHR11_1_CTG7', 'HSCHR15_1_CTG8', 'HSCHRX_2_CTG14', 'HSCHR19KIR_CA01-TB04_CTG3_1', 'HG1277_PATCH', 'HSCHR8_1_CTG1', 'HSCHR18_1_CTG1_1', 'HSCHR2_6_CTG1', 'HSCHRX_1_CTG3', 'HSCHR8_2_CTG1', 'HSCHR19KIR_FH05_B_HAP_CTG3_1', 'HG2285_HG106_HG2252_PATCH', 'HG2114_PATCH', 'HSCHR1_5_CTG3', 'HSCHR17_4_CTG4', 'HG2191_PATCH', 'HSCHR17_3_CTG1', 'HG705_PATCH', 'HSCHRX_2_CTG3', 'HG2225_PATCH', 'HSCHR6_1_CTG5', 'HSCHR7_3_CTG6', 'HG2471_PATCH', 'HG28_PATCH', 'HG2128_PATCH', 'HSCHR16_4_CTG3_1', 'HG2068_PATCH', 'HG2334_PATCH', 'HSCHR14_9_CTG1', 'HSCHR22_1_CTG4', 'HSCHR15_3_CTG3', 'HSCHR11_2_CTG3_1', 'HSCHR22_1_CTG3', 'HSCHR1_2_CTG3', 'HG1309_PATCH', 'HG2577_PATCH', 'HSCHR19KIR_FH15_B_HAP_CTG3_1', 'HSCHR3_3_CTG2_1', 'HSCHR17_11_CTG4', 'HG2072_PATCH', 'HSCHR15_3_CTG8', 'HG2231_HG2496_PATCH', 'HSCHR4_3_CTG12', 'HG2057_PATCH', 'HSCHR19KIR_CA01-TB01_CTG3_1', 'HSCHR12_4_CTG2', 'HSCHR4_9_CTG12', 'HSCHR17_8_CTG4', 'HG699_PATCH', 'HG2118_PATCH', 'HSCHR19_3_CTG3_1', 'HSCHR16_3_CTG1', 'HG2412_PATCH', 'HG2023_PATCH', 'HSCHR8_7_CTG1', 'HSCHR5_2_CTG1', 'HSCHR3_4_CTG2_1', 'HSCHR17_2_CTG4', 'HSCHR2_4_CTG1', 'HSCHR19KIR_0019-4656-B_CTG3_1', 'HSCHR4_1_CTG4', 'HSCHR11_3_CTG1', 'HG2115_PATCH', 'HSCHR19KIR_FH13_BA2_HAP_CTG3_1', 'HSCHR3_5_CTG1', 'HSCHR11_2_CTG1_1', 'HSCHR2_2_CTG7', 'HSCHR1_5_CTG32_1', 'HG2515_PATCH', 'HG23_PATCH', 'HG2571_PATCH', 'HSCHR11_1_CTG8', 'HSCHR7_1_CTG7', 'HG1535_PATCH', 'HSCHR7_2_CTG4_4', 'HSCHR19KIR_GRC212_AB_HAP_CTG3_1', 'HG2476_PATCH', 'HG2233_PATCH', 'HG2031_PATCH', 'HG2288_HG2289_PATCH', 'HSCHR4_5_CTG12', 'HG287_PATCH', 'HSCHR4_11_CTG12', 'HSCHR3_1_CTG3', 'HSCHR19KIR_RSH_BA2_HAP_CTG3_1', 'HSCHR18_5_CTG1_1', 'HG107_HG2565_PATCH', 'HSCHR19KIR_G248_BA2_HAP_CTG3_1', 'HSCHR11_1_CTG5', 'HSCHR15_9_CTG8', 'HSCHR11_1_CTG1_2', 'HSCHR21_2_CTG1_1', 'HG142_HG150_NOVEL_TEST', 'HSCHR19KIR_FH08_BAX_HAP_CTG3_1', 'HSCHR18_2_CTG2', 'HSCHR19KIR_FH05_A_HAP_CTG3_1', 'HSCHR3_8_CTG2_1', 'HSCHR6_1_CTG4', 'HSCHR3_6_CTG3', 'HSCHR17_1_CTG2', 'HSCHR15_2_CTG3', 'HG2576_PATCH', 'HSCHR5_3_CTG1', 'HSCHR3_6_CTG2_1', 'HG1398_PATCH', 'HSCHR16_1_CTG3_1', 'HSCHR13_1_CTG3', 'HG151_NOVEL_TEST', 'HSCHR19KIR_ABC08_A1_HAP_CTG3_1', 'HSCHR7_2_CTG1', 'HG2521_PATCH', 'HSCHR19KIR_FH06_BA1_HAP_CTG3_1', 'HSCHR10_1_CTG4', 'HSCHR19_3_CTG2', 'HSCHRX_3_CTG7', 'HSCHR19KIR_FH06_A_HAP_CTG3_1', 'HG1369_PATCH', 'HG986_PATCH', 'HSCHR22_1_CTG6', 'HSCHR19KIR_FH08_A_HAP_CTG3_1', 'HSCHR11_1_CTG2', 'HSCHR6_1_CTG3', 'HSCHR10_1_CTG6', 'HSCHR1_4_CTG31', 'HSCHR19KIR_T7526_BDEL_HAP_CTG3_1', 'HSCHR19KIR_LUCE_BDEL_HAP_CTG3_1', 'HSCHR3_9_CTG3', 'HSCHR12_4_CTG2_1', 'HSCHR20_1_CTG3', 'HSCHR1_1_CTG31', 'HG2116_PATCH', 'HSCHR2_7_CTG7_2', 'HSCHR10_1_CTG3', 'HSCHR11_1_CTG3_1', 'HSCHR14_2_CTG1', 'HSCHR3_1_CTG2_1', 'HSCHR13_1_CTG2', 'HG2239_PATCH', 'HSCHR10_1_CTG1', 'HSCHR5_4_CTG1', 'HSCHR17_1_CTG9', 'HSCHR19KIR_502960008-2_CTG3_1', 'HSCHR19KIR_RP5_B_HAP_CTG3_1', 'HSCHR11_1_CTG6', 'HG1298_PATCH', 'HSCHR22_3_CTG1', 'HSCHR3_4_CTG1', 'HSCHR6_1_CTG7', 'HSCHR12_8_CTG2_1', 'HSCHR22_7_CTG1', 'HG2140_PATCH', 'HSCHR2_3_CTG15', 'HSCHR18_ALT21_CTG2_1', 'HSCHR3_2_CTG2_1', 'HSCHR5_1_CTG5', 'HSCHR3_1_CTG1', 'HSCHR5_4_CTG1_1', 'HG2580_PATCH', 'HSCHR7_3_CTG1', 'HSCHR14_8_CTG1', 'HSCHR9_1_CTG3', 'HSCHR19KIR_7191059-2_CTG3_1', 'HSCHR19KIR_G248_A_HAP_CTG3_1', 'HG2111_PATCH', 'HSCHR19KIR_ABC08_AB_HAP_T_P_CTG3_1', 'HSCHR19KIR_LUCE_A_HAP_CTG3_1', 'HSCHR19KIR_RSH_A_HAP_CTG3_1', 'HSCHR19KIR_T7526_A_HAP_CTG3_1', 'HSCHR19KIR_FH15_A_HAP_CTG3_1', 'HSCHR19KIR_G085_A_HAP_CTG3_1', 'HSCHR19_2_CTG2', 'HSCHR19KIR_CA01-TA01_1_CTG3_1', 'HSCHR19KIR_FH13_A_HAP_CTG3_1', 'HSCHR12_1_CTG2_1', 'HSCHR16_3_CTG3_1', 'HSCHR13_1_CTG4', 'HSCHR13_1_CTG7', 'HSCHR19KIR_CA01-TA01_2_CTG3_1', 'HSCHR18_3_CTG2_1', 'HSCHR18_1_CTG2_1', 'HSCHR12_1_CTG1', 'HSCHR21_8_CTG1_1', 'HSCHR19KIR_502960008-1_CTG3_1', 'HSCHR3_4_CTG3', 'HG2058_PATCH', 'HSCHR1_8_CTG3', 'HSCHR1_2_CTG32_1', 'HG2237_PATCH', 'HSCHR3_8_CTG3', 'HG1445_PATCH', 'HG2419_PATCH', 'HSCHR18_2_CTG1_1', 'HSCHR5_6_CTG1', 'HSCHR4_1_CTG12', 'HSCHR3_7_CTG3', 'HSCHR3_7_CTG2_1', 'HSCHR19KIR_0019-4656-A_CTG3_1', 'HSCHR9_1_CTG6', 'HSCHR4_8_CTG12', 'HSCHR3_5_CTG3', 'HSCHR18_1_CTG1', 'HSCHR9_1_CTG1', 'HSCHR3_3_CTG3', 'HSCHR22_1_CTG1', 'HSCHR3_2_CTG3', 'HSCHR1_ALT2_1_CTG32_1', 'HSCHR2_1_CTG15', 'HSCHR2_2_CTG15', 'HSCHR19KIR_7191059-1_CTG3_1', 'HSCHR18_2_CTG2_1', 'HSCHR19KIR_HG2394_CTG3_1', 'HSCHR8_4_CTG7', 'HSCHR4_4_CTG12', 'HG1523_PATCH', 'HSCHR7_1_CTG4_4', 'HSCHR7_1_CTG1', 'HSCHR18_ALT2_CTG2_1', 'HSCHR17_3_CTG2', 'HSCHR19KIR_G085_BA1_HAP_CTG3_1', 'HG2067_PATCH', 'HSCHR19KIR_HG2393_CTG3_1', 'HSCHR22_4_CTG1', 'HSCHR22_6_CTG1', 'HSCHR19_1_CTG3_1', 'HSCHR19KIR_GRC212_BA1_HAP_CTG3_1', 'HG2046_PATCH', 'HSCHR11_1_CTG1_1', 'HSCHR12_9_CTG2_1', 'HSCHR22_5_CTG1', 'HSCHR12_3_CTG2_1', 'HSCHR6_1_CTG6', 'HG2176_PATCH', 'HG2249_PATCH', 'HG721_PATCH', 'HSCHR19KIR_HG2396_CTG3_1', 'HSCHR8_4_CTG1', 'HSCHR22_8_CTG1', 'HG2251_PATCH', 'HSCHRX_2_CTG12', 'HSCHR21_6_CTG1_1', 'HSCHR2_1_CTG5', 'HG2088_PATCH', 'HSCHR8_1_CTG6', 'HSCHR1_3_CTG3', 'HG1708_PATCH', 'HG2541_PATCH', 'HSCHR2_8_CTG7_2', 'HSCHR1_9_CTG3', 'HG2121_PATCH', 'HSCHR5_7_CTG1', 'HSCHR12_2_CTG2_1', 'HSCHR2_5_CTG7_2', 'HG2087_PATCH', 'HG2569_PATCH', 'HSCHR17_2_CTG1', 'HSCHR8_6_CTG1', 'HSCHR2_2_CTG1', 'HSCHR5_9_CTG1', 'HSCHR16_CTG2', 'HSCHR9_1_CTG7', 'HSCHR8_5_CTG7', 'HSCHR17_1_CTG4', 'HSCHR2_1_CTG7', 'HSCHR8_2_CTG7', 'HSCHR5_2_CTG5', 'HSCHR5_3_CTG5', 'HSCHR20_1_CTG1', 'HSCHR7_2_CTG7', 'HSCHR5_5_CTG1', 'HG1296_PATCH', 'HSCHR6_1_CTG2', 'HSCHR2_1_CTG7_2', 'HSCHR13_1_CTG8', 'HSCHR19KIR_ABC08_AB_HAP_C_P_CTG3_1', 'HG2578_PATCH', 'HG2104_PATCH', 'HSCHR12_1_CTG2', 'HSCHR2_1_CTG1', 'HG2494_PATCH', 'HSCHR4_2_CTG12', 'HSCHR12_6_CTG2_1', 'HSCHR7_1_CTG6', 'HSCHR20_1_CTG2', 'HSCHR17_12_CTG4', 'HSCHR21_4_CTG1_1', 'HG2155_PATCH', 'HSCHR3_5_CTG2_1', 'HSCHR4_1_CTG8_1', 'HSCHR18_4_CTG1_1', 'HSCHR2_4_CTG7_2', 'HSCHR1_2_CTG31', 'HSCHR2_3_CTG7_2', 'HSCHR1_1_CTG11', 'HSCHR12_2_CTG1', 'HSCHR3_3_CTG1', 'HG2217_PATCH', 'HSCHR17_9_CTG4', 'HG2408_PATCH', 'HSCHR11_2_CTG1', 'HG2133_PATCH', 'HSCHR18_1_CTG2', 'HG2554_PATCH', 'HSCHR13_1_CTG6', 'HSCHR8_7_CTG7', 'HSCHR22_1_CTG5', 'HSCHR5_3_CTG1_1', 'HG2062_PATCH', 'HG1311_HG2539_PATCH', 'HSCHR19KIR_CA04_CTG3_1', 'HSCHR19KIR_0010-5217-AB_CTG3_1', 'HG2499_PATCH', 'HSCHR22_1_CTG2', 'HSCHR2_2_CTG7_2', 'HG2442_PATCH', 'HSCHR4_2_CTG4', 'HSCHR17_3_CTG4', 'HG1395_PATCH', 'HSCHR16_2_CTG3_1', 'HSCHR19_6_CTG2', 'HSCHR17_6_CTG4', 'HG401_PATCH', 'HG2247_PATCH', 'HG2242_HG2243_PATCH', 'HG1384_PATCH', 'HSCHR5_1_CTG1', 'HSCHR21_5_CTG2', 'HSCHR6_1_CTG10', 'HSCHR16_5_CTG3_1', 'HSCHR6_8_CTG1', 'HSCHR12_5_CTG2_1', 'HSCHR6_1_CTG9', 'HSCHR21_3_CTG1_1', 'HSCHR22_2_CTG1', 'HG563_PATCH', 'HSCHR9_1_CTG2', 'HSCHR2_3_CTG1', 'HSCHR17_5_CTG4', 'HG2527_PATCH', 'HG1507_PATCH', 'HSCHR11_1_CTG3', 'HG1524_PATCH', 'HG2047_PATCH', 'HSCHR16_4_CTG1', 'HSCHR21_1_CTG1_1', 'HSCHR19_5_CTG2', 'HSCHR9_1_CTG4', 'HSCHR16_5_CTG1', 'HSCHR20_1_CTG4', 'HG1320_PATCH', 'HSCHR12_7_CTG2_1', 'HG1299_PATCH', 'HSCHR19_4_CTG2', 'HSCHR1_4_CTG32_1', 'HG1531_PATCH', 'HG1521_PATCH', 'HG460_PATCH', 'HSCHR19_2_CTG3_1', 'HSCHR12_5_CTG2', 'HG1047_PATCH', 'HSCHR13_1_CTG5', 'HSCHR8_6_CTG7', 'HG2216_PATCH', 'HG1046_PATCH', 'HG1506_PATCH', 'HG613_PATCH', 'HG1466_PATCH', 'HG1509_PATCH', 'HG2241_PATCH', 'HG494_PATCH', 'HG1817_1_PATCH', 'KI270728.1', 'KI270727.1', 'KI270442.1', 'KI270729.1', 'GL000225.1', 'KI270743.1', 'GL000008.2', 'GL000009.2', 'KI270747.1', 'KI270722.1', 'GL000194.1', 'KI270742.1', 'GL000205.2', 'GL000195.1', 'KI270736.1', 'KI270733.1', 'GL000224.1', 'GL000219.1', 'KI270719.1', 'GL000216.2', 'KI270712.1', 'KI270706.1', 'KI270725.1', 'KI270744.1', 'KI270734.1', 'GL000213.1', 'GL000220.1', 'KI270715.1', 'GL000218.1', 'KI270749.1', 'KI270741.1', 'GL000221.1', 'KI270716.1', 'KI270731.1', 'KI270751.1', 'KI270750.1', 'KI270519.1', 'GL000214.1', 'KI270708.1', 'KI270730.1', 'KI270438.1', 'KI270737.1', 'KI270721.1', 'KI270738.1', 'KI270748.1', 'KI270435.1', 'GL000208.1', 'KI270538.1', 'KI270756.1', 'KI270739.1', 'KI270757.1', 'KI270709.1', 'KI270746.1', 'KI270753.1', 'KI270589.1', 'KI270726.1', 'KI270735.1', 'KI270711.1', 'KI270745.1', 'KI270714.1', 'KI270732.1', 'KI270713.1', 'KI270754.1', 'KI270710.1', 'KI270717.1', 'KI270724.1', 'KI270720.1', 'KI270723.1', 'KI270718.1', 'KI270317.1', 'KI270740.1', 'KI270755.1', 'KI270707.1', 'KI270579.1', 'KI270752.1', 'KI270512.1', 'KI270322.1', 'GL000226.1', 'KI270311.1', 'KI270366.1', 'KI270511.1', 'KI270448.1', 'KI270521.1', 'KI270581.1', 'KI270582.1', 'KI270515.1', 'KI270588.1', 'KI270591.1', 'KI270522.1', 'KI270507.1', 'KI270590.1', 'KI270584.1', 'KI270320.1', 'KI270382.1', 'KI270468.1', 'KI270467.1', 'KI270362.1', 'KI270517.1', 'KI270593.1', 'KI270528.1', 'KI270587.1', 'KI270364.1', 'KI270371.1', 'KI270333.1', 'KI270374.1', 'KI270411.1', 'KI270414.1', 'KI270510.1', 'KI270390.1', 'KI270375.1', 'KI270420.1', 'KI270509.1', 'KI270315.1', 'KI270302.1', 'KI270518.1', 'KI270530.1', 'KI270304.1', 'KI270418.1', 'KI270424.1', 'KI270417.1', 'KI270508.1', 'KI270303.1', 'KI270381.1', 'KI270529.1', 'KI270425.1', 'KI270396.1', 'KI270363.1', 'KI270386.1', 'KI270465.1', 'KI270383.1', 'KI270384.1', 'KI270330.1', 'KI270372.1', 'KI270548.1', 'KI270580.1', 'KI270387.1', 'KI270391.1', 'KI270305.1', 'KI270373.1', 'KI270422.1', 'KI270316.1', 'KI270340.1', 'KI270338.1', 'KI270583.1', 'KI270334.1', 'KI270429.1', 'KI270393.1', 'KI270516.1', 'KI270389.1', 'KI270466.1', 'KI270388.1', 'KI270544.1', 'KI270310.1', 'KI270412.1', 'KI270395.1', 'KI270376.1', 'KI270337.1', 'KI270335.1', 'KI270378.1', 'KI270379.1', 'KI270329.1', 'KI270419.1', 'KI270336.1', 'KI270312.1', 'KI270539.1', 'KI270385.1', 'KI270423.1', 'KI270392.1', 'KI270394.1'])

In [124]:
# Replace the first 25 keys with mapping_table values
updated_fasta = {}

count = 0
for k, v in fasta.items():
    if count < 25:
        updated_fasta[mapping_table.get(k, k)] = v
        count += 1
    else:
        updated_fasta[k] = v

# Create true positive set

In [132]:
true_positives=[]
# Loop through the DataFrame and retrieve values of 'Chromosome', 'Start', and 'End' columns for each row
for index, row in chipseq_filtered_df.iterrows():
    chromosome = row['Chromosome']
    start = row['Start']
    end = row['End']
    true_positives.append(updated_fasta[chromosome][start-100:end+100].seq)

In [131]:
true_positives[1]

'CGCGGCCGCCTCCTCCTCCGAACGTGGCCGCCTCCGAACGTGGCCGCCGCCTCCTCCGAACGTGGCCGCTTCCGCAGCGCCCGGCGCAGGCCGCACTCCGCCACCAGGGGGCGCCACAGCTCCTCGCGCCGCCGCCTCCCGCAAACACAAAGAGCCGCGCGGCCACGACGGCCGCGTGCCCGGAGCGCCGGGGTCTTTCCTGGGCTCCAAAGTC'

# Create true negative set

## Create negative df by excluding the rows that belong to the ensembl_filtered df

In [139]:
# Merge the DataFrames based on specific columns and keep rows that do not exist in df_filtered
merged = df.merge(filtered_df, on=['Chromosome', 'Start', 'End', 'strand', 'score', 'name'], how='outer', indicator=True)
negative_df = merged[merged['_merge'] == 'left_only'].drop('_merge', axis=1)

In [140]:
negative_df

,Chromosome,Start,End,strand,score,name
0,chr10,11458,11472,+,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
1,chr12,547112,547126,-,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
6,chr4,5821787,5821801,+,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
7,chr1,9495407,9495421,+,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
10,chr16,12095359,12095373,+,24.2951,CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC
...,...,...,...,...,...,...
451726,chr1,243056957,243056971,+,10.0984,CTCF_4.49e-05_0.548_GCCTGGAGGGGCCAC
451728,chr1,245560998,245561012,+,10.0984,CTCF_4.49e-05_0.548_AACAGAAGGTGGCCC
451729,chr1,246738775,246738789,+,10.0984,CTCF_4.49e-05_0.548_CCCGCGAGGTGGAGG
451730,chr1,247423982,247423996,+,10.0984,CTCF_4.49e-05_0.548_AGCAGGAGAGGGAGC
451731,chr1,247470114,247470128,+,10.0984,CTCF_4.49e-05_0.548_ATCACAAGAGGTCAG

In [141]:
print(f"The percentage of the true negative set is {len(negative_df)/len(df)*100}% of the fimo results")

The percentage of the true negative set is 77.19222902074682% of the fimo results

In [142]:
true_negatives=[]
# Loop through the DataFrame and retrieve values of 'Chromosome', 'Start', and 'End' columns for each row
for index, row in negative_df.iterrows():
    chromosome = row['Chromosome']
    start = row['Start']
    end = row['End']
    true_negatives.append(updated_fasta[chromosome][start-100:end+100].seq)

In [150]:
print(f"We have {len(true_negatives)} negative sequences and {len(true_positives)} positive sequences")

We have 348702 negative sequences and 17936 positive sequences

In [145]:
print(f"True positives are {len(true_positives)/(len(true_negatives)+len(true_positives))*100}% of the dataset")

True positives are 4.892018830563117% of the dataset

In [146]:
print(f"True negatives are {len(true_negatives)/(len(true_negatives)+len(true_positives))*100}% of the dataset")

True negatives are 95.10798116943688% of the dataset

## Checking the length of the sequences

In [151]:
# Check the length of each string in the list
lengths_pos = [len(item) for item in true_positives]

In [158]:
max(lengths_pos),min(lengths_pos)

(214, 201)

In [159]:
# Check the length of each string in the list
lengths_neg = [len(item) for item in true_negatives]

In [ ]:
max(lengths_neg),min(lengths_neg)

# Combine the two sets in a df

In [161]:

# Create DataFrames for negative and positive sequences
true_negatives_df = pd.DataFrame({'data': true_negatives, 'class': 0})
true_positives_df= pd.DataFrame({'data': true_positives, 'class': 1})

# Concatenate both DataFrames into a single DataFrame
combined_df = pd.concat([true_negatives_df, true_positives_df], ignore_index=True)

# Display the combined DataFrame
print(combined_df)

                                                     data  class
0       GCCCCTGGGCCACGCCCACTCCCCCAAGCGGGGAAGGAGCTTCGCG...      0
1       CACCCACAACAGCCTGGACCCCGGACCGAGGTCCCCCTCGGTCGTC...      0
2       AAAACACTGACAGGAAAAGGGATGGACATGATTCCCAGAATCCTTC...      0
3       TAGTAGGTCATACCGCAGTGCCCACCGCAAGGGTGGCCACTGCGGA...      0
4       AGTTAATTTCGTTTGAATATATGGTTATTTGGGAGCTGGAGGTTGC...      0
...                                                   ...    ...
366633  CGGCCTATGACGGCGTCCTTGCGGAAGTACGGGTGCCGAGAGAAGC...      1
366634  TTGATCTTGTTTGTTACCTGGTTCTCAGTGAGCATAGGTAGTAGAC...      1
366635  TTGATCTTGTTTGTTACCTGGTTCTCAGTGAGCATAGGTAGTAGAC...      1
366636  CACCCGTTTCTATATTGAGGAGCTCCTCTCCATAAATAAAGCACAG...      1
366637  GGGGCGGTGGCGCGGAGTGGGCGGTGACTTCGGCGGGCGCCTCCCA...      1

[366638 rows x 2 columns]

In [219]:
# Export the DataFrame to a CSV file
combined_df.to_csv('data.csv', index=False)

In [176]:
# Shuffle the rows of the DataFrame
combined_df = combined_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [167]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, MaxPooling1D, Flatten, Dense




# Tokenizing sequences and converting to sequences of integers
tokenizer = Tokenizer(char_level=True)
tokenizer.fit_on_texts(combined_df['data'])
sequences = tokenizer.texts_to_sequences(combined_df['data'])



# Perform one-hot encoding for the padded sequences
#one_hot_sequences = np.array([one_hot_encode(seq) for seq in combined_df['data']])

In [ ]:
def one_hot_encode(sequence):
    encoding = {'A': [1, 0, 0, 0], 'T': [0, 1, 0, 0], 'G': [0, 0, 1, 0], 'C': [0, 0, 0, 1]}
    one_hot_sequence = [encoding.get(base, [0, 0, 0, 0]) for base in sequence]
    return np.array(one_hot_sequence)

In [193]:
# Find the maximum length of sequences
max_length = max(len(seq) for seq in combined_df['data'])

# Pad sequences to ensure they all have the same length
padded_sequences = [seq.ljust(max_length, 'N') for seq in combined_df['data']]

In [202]:
X= [one_hot_encode(sequence) for sequence in padded_sequences]
X=np.array(X)

In [203]:
y=np.array(combined_df['class'])

In [204]:
import torch
X = torch.from_numpy(X).type(torch.float)
y = torch.from_numpy(y).type(torch.float)

# View the first five samples
X[:5], y[:5]

(tensor([[[0., 0., 1., 0.],
          [1., 0., 0., 0.],
          [0., 1., 0., 0.],
          ...,
          [0., 1., 0., 0.],
          [0., 0., 0., 1.],
          [0., 0., 0., 1.]],

         [[0., 1., 0., 0.],
          [0., 0., 1., 0.],
          [0., 0., 1., 0.],
          ...,
          [0., 1., 0., 0.],
          [0., 1., 0., 0.],
          [0., 0., 1., 0.]],

         [[0., 0., 0., 1.],
          [0., 0., 0., 1.],
          [0., 0., 0., 1.],
          ...,
          [0., 1., 0., 0.],
          [0., 0., 1., 0.],
          [0., 0., 1., 0.]],

         [[0., 1., 0., 0.],
          [0., 0., 1., 0.],
          [0., 0., 1., 0.],
          ...,
          [0., 0., 1., 0.],
          [0., 0., 1., 0.],
          [0., 1., 0., 0.]],

         [[0., 0., 0., 1.],
          [0., 1., 0., 0.],
          [0., 0., 1., 0.],
          ...,
          [0., 0., 1., 0.],
          [1., 0., 0., 0.],
          [0., 0., 1., 0.]]]),
 tensor([0., 0., 0., 0., 0.]))

In [208]:
# Split data into train and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2, # 20% test, 80% train
                                                    random_state=42) # make the random split reproducible

len(X_train), len(X_test), len(y_train), len(y_test)

(293310, 73328, 293310, 73328)

# Set up device agnostic code

In [206]:
# Standard PyTorch imports
import torch
from torch import nn

# Make device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [212]:
# 1. Construct a model class that subclasses nn.Module
class ModelV0(nn.Module):
    def __init__(self):
        super().__init__()
        # 2. Create 2 nn.Linear layers capable of handling X and y input and output shapes
        self.layer_1 = nn.Linear(in_features=4, out_features=5) # takes in 2 features (X), produces 5 features
        self.layer_2 = nn.Linear(in_features=5, out_features=1) # takes in 5 features, produces 1 feature (y)
    
    # 3. Define a forward method containing the forward pass computation
    def forward(self, x):
        # Return the output of layer_2, a single feature, the same shape as y
        return self.layer_2(self.layer_1(x)) # computation goes through layer_1 first then the output of layer_1 goes through layer_2

# 4. Create an instance of the model and send it to target device
model_0 = ModelV0().to(device)
model_0

ModelV0(
  (layer_1): Linear(in_features=4, out_features=5, bias=True)
  (layer_2): Linear(in_features=5, out_features=1, bias=True)
)

# Set up loss function and optimizer

In [213]:
# Create a loss function
# loss_fn = nn.BCELoss() # BCELoss = no sigmoid built-in
loss_fn = nn.BCEWithLogitsLoss() # BCEWithLogitsLoss = sigmoid built-in

# Create an optimizer
optimizer = torch.optim.SGD(params=model_0.parameters(), 
                            lr=0.1)

In [220]:
# Calculate accuracy (a classification metric)
def accuracy_fn(y_true, y_pred):
    correct = torch.eq(y_true, y_pred).sum().item() # torch.eq() calculates where two tensors are equal
    acc = (correct / len(y_pred)) * 100 
    return acc

In [221]:
from sklearn.metrics import balanced_accuracy_score

# Function to calculate balanced accuracy
def balanced_accuracy(y_true, y_pred):
    return balanced_accuracy_score(y_true, y_pred) * 100

# Train the model

In [215]:
# View the frist 5 outputs of the forward pass on the test data
y_logits = model_0(X_test.to(device))[:5]
y_logits

tensor([[[-0.1812],
         [-0.4116],
         [-0.4116],
         ...,
         [-0.5166],
         [-0.5166],
         [-0.0459]],

        [[-0.4116],
         [-0.5166],
         [-0.4116],
         ...,
         [-0.4116],
         [-0.4116],
         [-0.4116]],

        [[-0.1812],
         [-0.4116],
         [-0.4116],
         ...,
         [-0.0459],
         [-0.4116],
         [-0.0459]],

        [[-0.0459],
         [-0.1812],
         [-0.5166],
         ...,
         [-0.0459],
         [-0.4116],
         [-0.4116]],

        [[-0.1812],
         [-0.1812],
         [-0.1812],
         ...,
         [-0.1812],
         [-0.5166],
         [-0.1812]]], grad_fn=<SliceBackward0>)

In [216]:
# Use sigmoid on model logits
y_pred_probs = torch.sigmoid(y_logits)
y_pred_probs

tensor([[[0.4548],
         [0.3985],
         [0.3985],
         ...,
         [0.3736],
         [0.3736],
         [0.4885]],

        [[0.3985],
         [0.3736],
         [0.3985],
         ...,
         [0.3985],
         [0.3985],
         [0.3985]],

        [[0.4548],
         [0.3985],
         [0.3985],
         ...,
         [0.4885],
         [0.3985],
         [0.4885]],

        [[0.4885],
         [0.4548],
         [0.3736],
         ...,
         [0.4885],
         [0.3985],
         [0.3985]],

        [[0.4548],
         [0.4548],
         [0.4548],
         ...,
         [0.4548],
         [0.3736],
         [0.4548]]], grad_fn=<SigmoidBackward0>)

In [217]:
# Find the predicted labels (round the prediction probabilities)
y_preds = torch.round(y_pred_probs)

# In full
y_pred_labels = torch.round(torch.sigmoid(model_0(X_test.to(device))[:5]))

# Check for equality
print(torch.eq(y_preds.squeeze(), y_pred_labels.squeeze()))

# Get rid of extra dimension
y_preds.squeeze()

tensor([[True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True]])

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<SqueezeBackward0>)

In [218]:
y_test[:5]

tensor([1., 0., 0., 0., 0.])